#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 29 21:11:57 2024

@author: oem
"""
import numpy as np
carpeta= "/home/oem/Desktop/uni/alc/tests/"
#CARGA DE ARCHIVO EN GRAFO
import numpy as np


def leerArchivo(m:str):
    carpeta= "/home/oem/Desktop/uni/alc/tests/"
    with open(carpeta+ m, 'r') as archivo:
        contenido = []

        for linea in archivo:
            x= linea.split()
            contenido.append(x)
       
            
    return contenido

W= leerArchivo("instagram_famosos_grafo.txt")


def linkeados(W:list):
    linkean=[] #guardo los elementos que apuntan a otro
    linkeados=[] #guardo los elementos apuntaodos
    conectados=[] #guardo una lista con los elementos a los que linkea cada uno
    for linea in W: 
        if len(linea)>1:
            w= linea[0]
            l= linea[1]
            if l not in linkeados:
                linkeados.append(l)
            m= [] #aca me agrupo los elementos a los que linkea w
            if w not in linkean:
                for elemento in W:
                    if len(elemento)<=1:
                        continue
                    elif elemento[0]==w:
                        m.append(elemento[1])
                    else: 
                        continue    
                linkean.append(w)
                conectados.append(m)
    #verifico que no haya un elemento que no linkea a nadie, si lo hay agrego una
    #lista a onectados (en su misma posicion) con un cwero
    for elemento in linkeados:
       if elemento not in linkean:
           x= int(elemento)-1
           conectados.insert(x,[0])
           print(conectados)
           print(linkean)
    return conectados

                
def conectividad(s: str):
    # Leer el archivo y obtener los datos
    A = leerArchivo(s)
    
    # Determinar los elementos conectados
    conectados = linkeados(A)
    n = len(conectados)
    
    # Crear una matriz de conectividad vacía
    Wt = np.zeros((n, n))
    
    # Llenar la matriz de conectividad transpuesta
    for i, elemento in enumerate(conectados):
        for x in elemento:
            if x != 0:
                posicion = int(x) - 1
                Wt[i, posicion] = 1
             
    W= np.transpose(Wt)
    return W      
            

seguidos = conectividad("instagram_famosos_grafo.txt")         

math= conectividad("mathworld_grafo.txt")
        
    
        
        
    
    